### ISSUE TITLE
Adding an SSL to the autonomous database APEX app to remove warning

### ISSUE THREAD

**Issue by alexesca** [oracle/adb-free#31]
How can I prevent this issue?

It affects my playwright tests, because some browsers have a default page to warn users that they are about to load an unsafe site. 

I get the "Not Secure" message when going to https://localhost:8443/ords/_/landing. I also get the chrome screen about navigating to an unsafe website. 

![image](https://github.com/user-attachments/assets/005d61a9-67c5-4794-aadd-ac1c74a9b535)
<img width="260" alt="image" src="https://github.com/user-attachments/assets/82b9f5ff-7bd2-4c39-9026-c4613da35389">

**Comment by aosingh** [comment]
@alexesca 

This is because we generate self-signed certificates for HTTPS on container start. 

You need to tell Chrome to trust the self-signed certs by clicking on "Advanced" and click on Proceed as shown in the screenshot below

![Screenshot 2024-11-20 at 9 54 15 AM](https://github.com/user-attachments/assets/fada3824-c73b-44b4-8e48-85f3da5a31bb)


That should take you to the landing page
![Screenshot 2024-11-20 at 9 57 16 AM](https://github.com/user-attachments/assets/53d3b021-bc0d-4c3e-bcca-a078067f3c0a)

**Comment by alexesca** [comment]
@aosingh I was able to solve the issue i was having with playwright by adding this to my setup

ignoreHTTPSErrors: true

See docs below 

https://playwright.dev/docs/api/class-testoptions
